config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :videos

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :videos

	validates :title, :image, presence: true
  validates :title, :uniqueness => {:case_sensitive => false}
  validates_each :title do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end

	mount_uploader :image, ImageUploader
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :category

  mount_uploader :thumbnail, ThumbnailUploader
  
  mount_uploader :video_link, VideoLinkUploader 
end

# do

#     def set_success(format, opts)
#       self.success = true
#     end
#   end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end
	
	def new
		@category = Category.new
	end

	def create
		@category = Category.new permitted_params
		if @category.save
			flash!(:success)
			redirect_to categories_path
		else
			render :new
		end
	end

	def edit
		@category = Category.find params[:id]
	end

	def update
		@category = Category.find params[:id]
		if @category.update permitted_params
			flash!(:success)
			redirect_to categories_path
		else
			render :edit
		end
	end

	def show
		
	end

	def destroy
	 	@category = Category.find params[:id]
	 	if @category.destroy
	 		flash!(:success)
	 		redirect_to categories_path
	 	else
	 		redirect_to categories_path
	 	end
	end 

	private
		def permitted_params
			params.require(:category).permit(:title, :image)
		end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
    @video = Video.new
    @categories = Category.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new video_params

    if @video.save
      redirect_to @video
    else
      render :new
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def list
    @video = Video.all
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])

    if @video.update update.params
      redirect_to videos_path
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])

    if @video.destroy
      redirect_to videos_path
    else
      redirect_to videos_path
    end
  end

  private
  def video_params
    params.require(:video).permit(:title, :description, :thumbnail, :category_id, :video_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/_form.haml
- if @category.errors.any?
  %h3
    = pluralize(@category.errors.count, "error")
    prohibited this category from being saved:
  %ul
    - @category.errors.full_messages.each do |msg|
      %li= msg

= form_for @category, :html => {:multipart => true} do |f|
  %p Title:
  = f.text_field :title, placeholder: "Title"
  %p Image:
  = f.file_field :image, name: "category[image]"
  %p
  = f.submit

app/views/categories/edit.haml
%h1 Edit Category
 
= render 'form'

app/views/categories/index.haml
%h1 Categories

#flash_messages= flash_messages(:close, :fade)

= link_to "Add New Categories", new_category_path

%br 
%table
	%thead
		%th Image
		%th Title
		%th Actions
	%tbody
		- @categories.each do |category|
			%tr
				%td= image_tag category.image_url(:thumb)
				%td= category.title

				%td= link_to "Edit", edit_category_path(category)
				%td= link_to "Delete", category_path(category),
					data: { confirm: "Are you sure you want to delete #{category.title} category?" },
					method: :delete

app/views/categories/new.haml
%h1 Add New Category

= render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practiceko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/_video.haml
%tr
  %td
    = image_tag video.thumbnail_url(:thumb)
  %td
    = link_to video_path(video) do
      = video.title 
  %td
    = video.description
  %td
    = link_to 'Edit', edit_video_path(video)
  %td
    = link_to "Delete", video_path(video),
          data: { confirm: "Are you sure you want to delete #{video.title}" },
          method: :delete

app/views/videos/_videos.haml
%table
  %thead
    %tr
      %th 
        Thumbnail
      %th 
        Title
      %th 
        Body
  %tbody
    - @videos.each do |video|
      =render 'video', video: video

app/views/videos/index.haml
%h1 Video List

= link_to "Upload New Video", new_video_path

=render 'videos', videos: @videos

app/views/videos/new.haml
%h1 Upload Videos

=form_for @video, :html => {:multipart => true} do |f|

  %p Title:
  =f.text_field :title, placeholder: "Title"

  %p Description:
  =f.text_area :description, placeholder: "Description"

  %p Category:
  =f.select :category_id, options_for_select(Category.all.collect{ |x|[x.title, x.id]  })

  %p Thumbnail:
  =f.file_field :thumbnail, name: "video[thumbnail]"
  
  %p Video:
  =f.file_field :video_link, name: "video[video_link]"

  %p 
    =f.submit

app/views/videos/show.haml
%h1 View Videos

=link_to 'Upload New Videos', new_video_path

%p Title: 
=@video.title

%p Video:
=video_tag("#{@video.video_link_url()}",controls: true, type: "video")

%p Body:
=@video.description

%p Tag:
=@video.category.title